name: FountainAI OpenAPI Parser CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run standard tests
      run: |
        python -m unittest discover -s tests
        # Automatically discover and run all standard test cases in `tests` folder

    - name: Run mock-specific tests
      run: |
        python -m unittest discover -s tests -p "test_parser_with_mocks.py"
        # Runs only mock-based tests to ensure mocks are handled separately

    - name: Run Linter (Flake8)
      run: |
        pip install flake8
        flake8 fountainai_openapi_parser

    - name: Run Type Checking (Mypy)
      run: |
        pip install mypy
        mypy fountainai_openapi_parser

    - name: Check Code Formatting (Black)
      run: |
        pip install black
        black --check fountainai_openapi_parser

    - name: Upload Test Coverage
      run: |
        pip install coverage
        coverage run -m unittest discover -s tests
        coverage report
        coverage xml
        # Optional upload to coverage tracking service