name: FountainAI OpenAPI Parser CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Auto-format and Lint Fix (Black, Flake8)
        run: |
          pip install black flake8
          black --line-length 100 fountainai_openapi_parser
          flake8 --exit-zero fountainai_openapi_parser --max-line-length=100 --ignore=E203,W503
        # Note: `--exit-zero` ignores errors in Flake8 so that it only applies formatting without failing the job.

      - name: Run Type Checking (Mypy)
        run: |
          pip install mypy types-PyYAML
          mypy fountainai_openapi_parser/models
          mypy fountainai_openapi_parser

      - name: Run Tests and Upload Coverage
        run: |
          pip install coverage
          coverage run -m unittest discover -s tests
          coverage run -m unittest discover -s tests/models
          coverage report
          coverage xml

      - name: Commit changes (if any)
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && echo "No changes to commit" || git commit -m "CI: Auto-format code with Black and apply lint fixes"
          git push
